<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fertilizer Order Form</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <div class="container mt-7">
        <div class="row">
            <div class="col-md-6">
                <!-- Add Images Here -->
                <h2>Images</h2>
                <img src="path/to/image1.jpg" alt="Image 1" class="img-fluid">
                <img src="path/to/image2.jpg" alt="Image 2" class="img-fluid">
                <!-- Add more images if needed -->
            </div>
            <div class="col-md-6">
                <!-- Fertilizer Calculator Form -->
                <h2>Fertilizer Calculator</h2>
                <form method="POST" action="orderFertiVal.php">
                    <!-- Add input fields for GN Division and NIC -->
                    <div class="form-group">
                        <label for="gnDivision">GN Division:</label>
                        <input type="text" name="gnDivision" id="gnDivision" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="nic">NIC:</label>
                        <input type="text" name="nic" id="nic" class="form-control" required>
                    </div>

                    <!-- The fertilizer table will be generated by PHP code -->
                    <div id="fertilizerTableContainer">
                        <!-- The fertilizer table will be inserted here -->
                    </div>

                    <!-- Display the total price of the order -->
                    <div id="totalPriceContainer">
                        <!-- The total price of the order will be inserted here -->
                    </div>

                    <!-- Button to submit the order -->
                    <button type="submit" name="submitOrder" class="btn btn-primary">Submit Order</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Add Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Add your custom JavaScript code here (if needed) -->
</body>

</html>
